### ISSUE TITLE
!recent 增加index参数以便查看最新的第几个成绩

### ISSUE THREAD

**Issue by Exsper** [Monodesu/KanonBot#1]
## 必要性
在群里看到有这种需求，有时需要查看第二个最新成绩
## 可行性
osu官方API提供了玩家最近成绩的查询接口
## 指令
```!re2```可能会与id冲突，可以考虑```!re #2```

**Comment by Monodesu** [comment]
收到，下个版本添加

**Comment by Monodesu** [comment]
已在新猫中添加
