### ISSUE TITLE
!badge set/info无法设置／查看list中最后一个badge.

### ISSUE THREAD

**Issue by glacc** [Monodesu/KanonBot#13]
猜测问题可能出现在 [KanonBot/src/functions/osu/badge.cs](https://github.com/Monodesu/KanonBot/blob/master/src/functions/osu/badge.cs) 中 badgeNum 与 owned_badges.Count 的大小比较中：

private static async Task Set(Target target, string cmd, AccInfo accinfo) 中

163-167行和220-224行

> ``//检查用户是否拥有此badge``
> ``if (owned_badges.Count <= badgeNum)``
> ``{``
> ``　target.reply($"你好像没有编号为 {badgeNum} 的badge呢..."); return;``
> ``}``

是否应该用 < 而不是 <= ？

**Comment by glacc** [comment]
![](https://user-images.githubusercontent.com/54176497/200157616-2d11e351-7683-4b67-9b7e-a624f4fb0142.png)

**Comment by Monodesu** [comment]
https://github.com/Monodesu/KanonBot/commit/cb44e7ab36cb1e9c2498d83b15ae5d7256b40d43

**Comment by glacc** [comment]
抱歉…一楼列函数时只列了一个忘了 !badge info [num] 对应的 private static async Task Info(Target target, string cmd, AccInfo accinfo) 函数，其中也有同样的问题

**Comment by glacc** [comment]
> [cb44e7a](https://github.com/Monodesu/KanonBot/commit/cb44e7ab36cb1e9c2498d83b15ae5d7256b40d43)

抱歉…一楼列函数时只列了一个忘了 !badge info [num] 对应的 private static async Task Info(Target target, string cmd, AccInfo accinfo) 函数，其中也有同样的问题

**Comment by Monodesu** [comment]
下次提交新功能时修复

**Comment by glacc** [comment]
谢谢
