### ISSUE TITLE
使用说明？

### ISSUE THREAD

**Issue by TTsdzb** [Monodesu/KanonBot#14]
在<https://info.desu.life/?p=383>貌似提到了可以用自己的账号：

> 如要托管一个实例，请在go-cqhttp的设置文件config.yml中，将servers字段下的ws-reverse启用，并将universal地址设置为ws://botws.desu.life:65000即可。

但是不清楚什么原因，Websocket 一收到消息就连接超时，也不会收到回复。

随后我找到了这个仓库，但不清楚如何配置。

如果允许使用自己的账号和 go-cqhttp，但需要提前申请，能否提前说明？

如果允许自己运行，能否给出配置、运行需求的说明？

谢谢。

**Comment by Monodesu** [comment]
无需申请，要注意的是，需要在go-cqhttp配置中将post-type改为array，后端才可正常处理消息，否则会直接断开连接。

**Comment by Monodesu** [comment]
可以自己搭建后端环境，但是本仓库缺少需要的有版权限制的字体以及数据库结构文件，有需要的话请通知我，我再上传除有版权限制以外的所有资源文件

**Comment by TTsdzb** [comment]
> 无需申请，要注意的是，需要在go-cqhttp配置中将post-type改为array，后端才可正常处理消息，否则会直接断开连接。

可以了，感谢
