### ISSUE TITLE
无法连接desu.life

### ISSUE THREAD

**Issue by Xian0Grem** [Monodesu/KanonBot#16]
该网站desu.life/目前处于离线状态。[Cloudflare 的 Always Online™显示了来自](https://www.cloudflare.com/always-online/)[Internet Archive 的 Wayback Machine](https://archive.org/web/)的该网页的快照。要检查实时版本，请单击“刷新”。

我的问题吗？我这几天连不上了

**Comment by Monodesu** [comment]
服务器转移，事先在群里通知过了，今晚或者明天能恢复

**Comment by Xian0Grem** [comment]
这样啊，抱歉我不在群里没看到
