### ISSUE TITLE
为避免重复造轮子，有兴趣一同使用与改进我的框架吗

### ISSUE THREAD

**Issue by Milkitic** [Monodesu/KanonBot#2]
您若有兴趣我们可以讨论一下
我也是osuer哈，做的机器人是mapping向的
我的框架项目: https://github.com/Milkitic/MilkiBotFramework 
我的机器人项目(叫黄花菜，重构中，在develop分支): https://github.com/Milkitic/Daylily/tree/develop

**Comment by Monodesu** [comment]
抱歉，目前本bot代码处于高度耦合状态，考虑到多种因素，暂无法使用您编写的框架。
