### ISSUE TITLE
score 四模式独立模板

### ISSUE THREAD

**Issue by Exsper** [Monodesu/KanonBot#7]
可以考虑四模式分别用各自不同的成绩模板

各模式有不同的pp分量

mania的acc阶梯可以改为得分阶梯

**Comment by fantasyzhjk** [comment]
新的面板是考虑到各种模式的，关于得分阶梯能具体说明下吗

**Comment by Exsper** [comment]
> 新的面板是考虑到各种模式的，关于得分阶梯能具体说明下吗

按[mania的pp计算公式](https://github.com/ppy/osu-performance/blob/master/src/performance/mania/ManiaScore.cpp)，pp与acc无关，只与得分有关，pp阶梯可以设置从当前得分到满分（无mod为一百万，有mod需要乘以mod得分系数）的阶梯，比如得分为600,000，阶梯可以设为600,000，700,000，800,000，900,000，1,000,000

满分计算
```
    得分系数 = 1.0;
    if (是转谱) {
      diff = 游玩键数 - 谱面键数
      if (diff > 0) 得分系数 *= 0.9;
      if (diff < 0) 得分系数 *= 0.9 + 0.04 * diff;
    }
    得分系数 *= Math.Pow(0.5, EZ + HT + NF);
    满分 = 1,000,000 * 得分系数
```

**Comment by Exsper** [comment]
因pp系统改动，该issue的建议不再适合当前版本。
